spring.application.name=banking
server.port=8080

# ===========================
# POSTGRESQL VERITABANI BAĞLANTISI
# ===========================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE AYARLARI
# ===========================
# "update" modunda tablo yoksa otomatik oluşturur, varsa günceller (Code First)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# BAŞLANGIÇ VERİSİ
# ===========================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
